"""Add tiredness_level to mood_logs

Revision ID: 3ced89579332
Revises: 
Create Date: 2025-09-01 14:20:05.657834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ced89579332'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('hydration_logs', 'daily_goal',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.add_column('mood_logs', sa.Column('tiredness_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood_logs', 'tiredness_level')
    op.alter_column('hydration_logs', 'daily_goal',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
